events {
    worker_connections 1024;
}

http {
    upstream grafana {
        server mi-proyecto-grafana-1:3000;
    }
    
    server {
        listen 80;
        server_name localhost;
        
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
        
        location /grafana/ {
            proxy_pass http://grafana/;
            proxy_set_header Host $http_host;
        }
        
        location /nginx_status {
            stub_status on;
            access_log off;
        }
        
        location /health {
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }
    }
}
