apiVersion: 1
datasources:
  - name: Tempo
    uid: TEMPO_DS
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      tracesToLogs:
        datasourceUid: LOKI_DS
        mappedTags:
          - { key: "service.name", value: "service" }
        mapTagNamesEnabled: true
