groups:
- name: pg
  rules:
  - alert: PostgresDown
    expr: pg_up == 0
    for: 1m
    labels: {severity: critical}
    annotations:
      summary: "Postgres exporter down"
      description: "pg_up=0 en {{ $labels.instance }}"
