[databases]
# Conecta a Postgres dentro del compose
appdb   = host=db port=5432 dbname=appdb pool_mode=transaction
postgres= host=db port=5432 dbname=postgres

[pgbouncer]
listen_addr = 0.0.0.0
listen_port = 6432

# Autenticación por MD5 usando el auth_file que montamos
auth_type = md5
auth_file = /etc/pgbouncer/userlist.txt

# Admins que pueden usar la DB "pgbouncer"
admin_users = postgres

# Pooling recomendado
pool_mode = transaction
default_pool_size = 20
max_client_conn = 200

# Evita problemas con parámetros de inicio
ignore_startup_parameters = extra_float_digits
