{
 "title": "Observability - Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Targets UP (Prometheus)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(up)" }
   ]
  },
  {
   "title": "Probes OK (Blackbox)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "targets": [
    { "expr": "sum(probe_success)" }
   ]
  },
  {
   "title": "Latencia (Blackbox) media 5m",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time(probe_duration_seconds[5m])"
    }
   ]
  },
  {
   "title": "Tasa de errores (logs/min)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "(sum(rate({}|= \"error\"[1m])) or vector(0))"
    }
   ]
  },
  {
   "title": "Eventos de log/min (Total)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "(sum(rate({}[1m])) or vector(0))"
    }
   ]
  }
 ]
}