{
 "title": "Ayuntamiento - Servicios críticos",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Disponibilidad (últimas 24h) %",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time(probe_success[24h]) * 100"
    }
   ]
  },
  {
   "title": "HTTP status (último scrape)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "max by (target) (probe_http_status_code)"
    }
   ]
  },
  {
   "title": "Latencia HTTP (seg) - 1h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "avg_over_time(probe_duration_seconds[5m])"
    }
   ]
  },
  {
   "title": "Errores (logs/min)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "(sum(rate({}|= \"error\"[1m])) or vector(0))"
    }
   ]
  },
  {
   "title": "Eventos de log/min (Total)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "(sum(rate({}[1m])) or vector(0))"
    }
   ]
  }
 ]
}