{
 "title": "Infra - Contenedores",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU por contenedor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total[3m]))"
    }
   ]
  },
  {
   "title": "Memoria por contenedor (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "container_memory_usage_bytes" }
   ]
  },
  {
   "title": "Containers UP",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count(container_last_seen > time() - 60)"
    }
   ]
  }
 ]
}