global:
  resolve_timeout: 5m
  smtp_smarthost: 'mailhog:1025'
  smtp_from: 'alertas@mi-proyecto.local'

route:
  group_by: ['alertname','instance']
  group_wait: 15s
  group_interval: 2m
  repeat_interval: 4h
  receiver: 'mailhog'

receivers:
  - name: 'mailhog'
    email_configs:
      - to: 'admin@example.com'
