global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'rhinometric-api'
    static_configs:
      - targets: ['rhinometric-api:3001']
    metrics_path: '/metrics'
    scrape_interval: 15s
  
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana1:3000', 'grafana2:3000']
  
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
