#!/bin/bash
# Rhinometric v2.1.0 - Oracle Cloud Auto-Install Script
# Este script se ejecuta automáticamente al crear la VM

set -e  # Exit on error

echo "========================================="
echo "🦏 RHINOMETRIC v2.1.0 - AUTO-INSTALL"
echo "========================================="
echo ""
echo "OS: $(lsb_release -ds)"
echo "Kernel: $(uname -r)"
echo "Date: $(date)"
echo ""

# ========================================
# 1. Update System
# ========================================

echo "[1/8] Actualizando sistema operativo..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get upgrade -y -qq

# ========================================
# 2. Install Dependencies
# ========================================

echo "[2/8] Instalando dependencias..."
apt-get install -y -qq \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release \
    git \
    jq \
    wget \
    unzip

# ========================================
# 3. Install Docker
# ========================================

echo "[3/8] Instalando Docker..."

# Add Docker GPG key
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

# Add Docker repository
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

# Install Docker
apt-get update -qq
apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin

# Start Docker
systemctl start docker
systemctl enable docker

# Add ubuntu user to docker group
usermod -aG docker ubuntu

echo "✅ Docker $(docker --version) instalado"

# ========================================
# 4. Clone Rhinometric Repository
# ========================================

echo "[4/8] Clonando repositorio Rhinometric..."

cd /home/ubuntu
git clone https://github.com/Rafael2712/mi-proyecto.git
cd mi-proyecto/infrastructure/mi-proyecto/rhinometric-trial-v2.1.0-universal

# Change ownership to ubuntu user
chown -R ubuntu:ubuntu /home/ubuntu/mi-proyecto

# ========================================
# 5. Configure Environment
# ========================================

echo "[5/8] Configurando variables de entorno..."

cat > .env <<EOF
# Rhinometric v2.1.0 Configuration
# Generated by Terraform on $(date)

# Grafana Configuration
GRAFANA_USER=admin
GRAFANA_PASSWORD=${grafana_password}

# PostgreSQL Configuration
POSTGRES_USER=rhinometric
POSTGRES_PASSWORD=${postgres_password}
POSTGRES_DB=rhinometric

# Redis Configuration
REDIS_PASSWORD=${redis_password}

# Paths (Oracle Cloud Ubuntu)
HOME=/home/ubuntu
DATA_PATH=/var/lib/rhinometric

# Rhinometric Configuration
RHINOMETRIC_MODE=trial
RHINOMETRIC_VERSION=2.1.0

# Network
HOST_IP=0.0.0.0

# Resource Limits (Oracle Cloud E4.Flex 4 OCPU / 16 GB RAM)
GRAFANA_CPU_LIMIT=1.0
GRAFANA_MEMORY_LIMIT=2048M
PROMETHEUS_CPU_LIMIT=2.0
PROMETHEUS_MEMORY_LIMIT=4096M
LOKI_CPU_LIMIT=1.0
LOKI_MEMORY_LIMIT=2048M
TEMPO_CPU_LIMIT=1.0
TEMPO_MEMORY_LIMIT=1024M
POSTGRES_CPU_LIMIT=2.0
POSTGRES_MEMORY_LIMIT=4096M
REDIS_CPU_LIMIT=0.5
REDIS_MEMORY_LIMIT=512M

# Logging
LOG_LEVEL=info
EOF

chown ubuntu:ubuntu .env

echo "✅ .env configurado"

# ========================================
# 6. Create Data Directories
# ========================================

echo "[6/8] Creando directorios de datos..."

mkdir -p /var/lib/rhinometric/{prometheus,grafana,loki,tempo,postgres,redis}
chown -R ubuntu:ubuntu /var/lib/rhinometric

echo "✅ Directorios creados"

# ========================================
# 7. Pull Docker Images
# ========================================

echo "[7/8] Descargando imágenes Docker (esto toma 5-10 minutos)..."

cd /home/ubuntu/mi-proyecto/infrastructure/mi-proyecto/rhinometric-trial-v2.1.0-universal

# Pull images as ubuntu user
su - ubuntu -c "cd /home/ubuntu/mi-proyecto/infrastructure/mi-proyecto/rhinometric-trial-v2.1.0-universal && docker compose -f docker-compose-v2.1.0.yml pull" 2>&1 | tee /var/log/rhinometric-pull.log

echo "✅ Imágenes descargadas"

# ========================================
# 8. Start Rhinometric Stack
# ========================================

echo "[8/8] Iniciando Rhinometric v2.1.0..."

# Start as ubuntu user
su - ubuntu -c "cd /home/ubuntu/mi-proyecto/infrastructure/mi-proyecto/rhinometric-trial-v2.1.0-universal && docker compose -f docker-compose-v2.1.0.yml up -d" 2>&1 | tee /var/log/rhinometric-start.log

# Wait for services to be healthy
echo "⏳ Esperando servicios (60 segundos)..."
sleep 60

# Verify containers
RUNNING=$(docker ps | grep rhinometric | wc -l)
echo "✅ Contenedores en ejecución: $RUNNING/17"

# ========================================
# 9. Configure Systemd Service (autostart en boot)
# ========================================

echo "Configurando systemd service..."

cat > /etc/systemd/system/rhinometric.service <<EOF
[Unit]
Description=Rhinometric Monitoring Stack v2.1.0
Requires=docker.service
After=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
User=ubuntu
WorkingDirectory=/home/ubuntu/mi-proyecto/infrastructure/mi-proyecto/rhinometric-trial-v2.1.0-universal
ExecStart=/usr/bin/docker compose -f docker-compose-v2.1.0.yml up -d
ExecStop=/usr/bin/docker compose -f docker-compose-v2.1.0.yml down

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable rhinometric.service

echo "✅ Systemd service configurado"

# ========================================
# 10. Health Check
# ========================================

echo ""
echo "========================================="
echo "🔍 VERIFICACIÓN DE SERVICIOS"
echo "========================================="

PUBLIC_IP=$(curl -s http://169.254.169.254/opc/v1/instance/metadata | jq -r .publicIp)

echo ""
echo "✅ Instalación completada!"
echo ""
echo "📊 Acceso a Rhinometric:"
echo "   🎨 Grafana:        http://$PUBLIC_IP:3000"
echo "      Usuario: admin"
echo "      Password: ${grafana_password}"
echo ""
echo "   🔌 API Connector:  http://$PUBLIC_IP:8091"
echo "   📊 Prometheus:     http://$PUBLIC_IP:9090"
echo ""
echo "🐳 Docker containers:"
docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" | grep rhinometric
echo ""
echo "📝 Logs en:"
echo "   /var/log/rhinometric-pull.log"
echo "   /var/log/rhinometric-start.log"
echo ""
echo "🔧 Comandos útiles:"
echo "   docker ps | grep rhinometric"
echo "   docker compose -f docker-compose-v2.1.0.yml logs -f"
echo "   docker compose -f docker-compose-v2.1.0.yml restart"
echo ""
echo "========================================="
echo "🦏 RHINOMETRIC v2.1.0 - LISTO!"
echo "========================================="
