http:
  middlewares:
    auth:
      basicAuth:
        users:
          - "admin:$2y$10$DjmQzTdoJHclxLOz.oaFT.s8xWbOUvN9AuT9VpBYFZFl9/1XnG7gO"

    security:
      headers:
        accessControlAllowOriginList:
          - "https://rhinometric.com"
          - "https://www.rhinometric.com"
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        frameDeny: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000

    compress:
      compress: {}

tls:
  options:
    default:
      minVersion: "VersionTLS12"
      maxVersion: "VersionTLS13"
