"""
SQLAlchemy model for Backup artifacts.
Phase 1: Manual backup of external services configuration.
"""

import uuid as _uuid
from sqlalchemy import Column, String, Integer, DateTime, Text, BigInteger
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.sql import func
from database import Base


class BackupArtifact(Base):
    """Represents a single backup file generated by the platform."""
    __tablename__ = "backup_artifacts"

    id = Column(UUID(as_uuid=True), primary_key=True, default=_uuid.uuid4)
    filename = Column(String(500), nullable=False, index=True)
    status = Column(String(50), nullable=False, default="in_progress", index=True)  # in_progress, completed, failed
    backup_type = Column(String(50), nullable=False, default="manual")  # manual, scheduled (future)
    size_bytes = Column(BigInteger, nullable=True)
    storage_path = Column(Text, nullable=False)
    created_by = Column(String(255), nullable=False)
    error_message = Column(Text, nullable=True)
    records_exported = Column(Integer, nullable=True, default=0)
    platform_version = Column(String(50), nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    def to_dict(self):
        return {
            "id": str(self.id),
            "filename": self.filename,
            "status": self.status,
            "backup_type": self.backup_type,
            "size_bytes": self.size_bytes,
            "storage_path": self.storage_path,
            "created_by": self.created_by,
            "error_message": self.error_message,
            "records_exported": self.records_exported,
            "platform_version": self.platform_version,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }
